# -*- coding: utf-8 -*-
"""IF_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1geBCtPiXYRRBxyUseO268HA4o2BJQtE1
"""

#leia nota1
#leia nota2

#calcule a media
#se a media>=7
#escreva aprovado
#senao
#escreva Reprovado

nota1 = 10
nota2 = 9

media = (nota1+nota2)/2

if(media>=7):
  print("Aprovado")
else:
  print("Reprovado")