# -*- coding: utf-8 -*-
"""LIstadeIF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RUkBt5GxKG_I85ml66rNK14IgRIZ-Q4B
"""

x=4
x1=9
x2=5


xResult=(((2+5)*3)+x+5)<x1
print(xResult)

xResult=(((2+5)*3)+(x+5+x1)==(x+6+x2*2))
print(xResult)

xResult=(((2+5)*3)+(x+5<x1)==(x==6+x2*2))
print(xResult)

xResult=(((3*6)+x-3)<x2)
print(xResult)

xResult=((((7*8)>(x+4>x1)<x!=2+x2*9)))
print(xResult)

xResult=((((7*8)>(x+4-x1)<(x*2+x2*9))))
print(xResult)

if(n<20) and (n>30):
  print('n esta fora do intervalo')

n=int(input("Digite um numero "))
if(n>20) and (n<30):
  print("n esta entre 20 e 30")
else:
  print('n esta fora do intervalo')

a = int(input("Digite o valor de a: "))
b = int(input("Digite o valor de b: "))
if (a>10) and (b<=5):
  print("True")
else:
  print("false")