# -*- coding: utf-8 -*-
"""Exercicios_While.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SVzwertPghN5sTo0mqK5JW3r4rGDPCwD
"""

salario = 1000
while salario<5000:
    salario +=100
    print(f"O valor do salario {salario}")

nota = int(input("Digite a Nota: "))
while True:
    if nota>=0 and nota<=10:
        print("Valor valido")
    else:
        print("Valor invalido")
    break

qtdN=int(input("Digite a quantidade de vezes do loop: "))
qtd=1
while True:
    n = float(input("Digite a Nota: "))
    soma =+ n
    total = soma/5
    if qtd==qtdN:
        break
    qtd+=1
print(input(f"A media é: {total}"))

while True:
    nome = input("Digite o seu Nome: ")
    senha = input("Digite a sua senha: ")
    if nome==senha:
        print("A Senha Não deve ser igual ao Nome!!")
    else:
        break

sal_incial = float(input("Digite o valor do Salario: "))
percentual = 0.015
ano = int(input("Digite o ano final: "))
ano_incial = 1996

while ano_incial<=ano:
    percentual*=2
    calculo_salario = sal_incial * (1+percentual)
    print(f"O valor do salario do ano {ano_incial} e {calculo_salario:.2f}")
    ano_incial+=1

n=int(input("Digite a quantidade de vezes que o loopinf ira repetir: "))
count=0
while count<=n:
    nome = input("Digite o Nome: ")
    idade = int(input("Digite a Idade: "))
    salario = input("Digite o Salario: ")
    sexo = input("Digite o seu sexo: ")
    estado_civil = input("Digite o estado civil: ")
    if len(nome)>3:
        print(f"Nome: {nome}")
    else:
        print("O nome contem três letras ou menos")
    if (idade>0) and (idade<=150):
        print(f"Idade: {idade}")
    if(sexo=="f") or (sexo=="m"):
        print(f"Sexo: {sexo}")
    if(estado_civil=="s"):
        print(f"Estado Civil: {estado_civil}")
    if(estado_civil=="c"):
        print(f"Estado Civil: {estado_civil}")
    if(estado_civil=="v"):
        print(f"Estado Civil: {estado_civil}")
    if(estado_civil=="d"):
        print(f"Estado Civil: {estado_civil}")
    count += 1
    if(count==n):
        break

popA= 80000
popB= 200000
percA = 0.03
percB = 0.015
count=0

while popA<=popB:
    popA = popA * (1 + percA)
    popB = popB * (1 + percB)
    count+=1
print(f"A quantidade de anos que demorou para mudar o cresimento e: {count}")

fat = int(input("Digite o numero: "))
count =1
resultado =1

while count<=fat:
    if fat==0:
        print("1")
    elif fat==1:
        print("1")
    resultado *= count
    count+=1
    print(resultado)

media = 0
count = 1
soma = 0
num1=int(input("Digite o parametro final: "))

while count<=num1:
    num = int(input("Digite um numero: "))
    if num==0:
        break
    else:
        soma += num
        media=soma/count
        count += 1
print(media)

n_enesimo = int(input("Digite o Enesimo numero: "))
x1 = 1
x2 = 1
prox = x2
count = 0

while count<=n_enesimo:
    if(count==0):
        print(f"{x1}")
    print(prox)
    count+=1
    x1,x2 = x2,prox
    prox = x1+x2

total =0
troco =0.0
valor_Dinheiro = float(input("Digite o valor em Dinheiro: "))
fim_compra=1
while True:
    prod = float(input("Digite o valor do produto: "))
    fim_compra = int(input("Finalizar compra"))
    total +=prod
    troco = valor_Dinheiro - total
    if(fim_compra==0):
        break
print(f"Valor do produto e: {round(prod,2)}")
print(f"Total da compra e: {round(total)}")
print(f"Valor em dinheiro a ser Pago e : {round(valor_Dinheiro)}")
print(f"O valor do troco e {round(troco,2)}")

codigo1, valor = 100, 1.20
codigo2, valor1 = 101, 1.30
codigo3,valor2 = 102, 1.50
codigo4, valor3 = 103, 1.20
codigo5, valor4 = 104, 1.30
codigo6, valor5 = 105, 1.00
fim_compra = 1
pedido = ""
quantidade = 0

while True:
    codigo = int(input("Digite o Codigo do Pedido: "))
    if codigo1 == 100:
        pedido1 = "Cachorro Quente"
        quantidade1 = int(input("Digite a quantidade do pedido: "))
        valor_total1 = valor * quantidade1
        print(f"Foi comprado {pedido1} e a quatidade foi {quantidade1} o total da compra e: {valor_total1:.2f}")
    if codigo2==101:
            pedido2 = "Bauru Simples"
            quantidade2 = int(input("Digite a quantidade do pedido: "))
            valor_total2 = valor1 * quantidade2
            print(f"Foi comprado {pedido2} e a quatidade foi {quantidade2} o total da compra e: {valor_total2:.2f}")
    if codigo2==102:
            pedido3 = "Bauru com ovo"
            quantidade3 = int(input("Digite a quantidade do pedido: "))
            valor_total3 = valor2 * quantidade
            print(f"Foi comprado {pedido3} e a quatidade foi {quantidade2} o total da compra e: {valor_total3:.2f}")
    if codigo2==103:
            pedido4 = "Hambúrguer"
            quantidade3 = int(input("Digite a quantidade do pedido: "))
            valor_total3 = valor3 * quantidade3
            print(f"Foi comprado {pedido4} e a quatidade foi {quantidade3} o total da compra e: {valor_total3:.2f}")
    if codigo3==104:
            pedido5 = "Cheeseburguer"
            quantidade5 = int(input("Digite a quantidade do pedido: "))
            valor_total5 = valor4 * quantidade
            print(f"Foi comprado {pedido5} e a quatidade foi {quantidade5} o total da compra e: {valor_total5:.2f}")

    if codigo4==105:
            pedido6 = "Refrigerante"
            quantidade6 = int(input("Digite a quantidade do pedido: "))
            valor_total6 = valor5 * quantidade6
            print(f"Foi comprado {pedido6} e a quatidade foi {quantidade6} o total da compra e: {valor_total6:.2f}")
    fim_compra = int(input("E fim da compra: "))
    if(fim_compra==0):
        break